name: Manual workflow
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Select environment
        options:
          - stage
          - non_prod

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run maven command
        uses: actions/checkout@v2
      - name: Build
        run: mvn clean install -Dkarate.env="${{ github.event.inputs.environment }}"