name: Manual workflow
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Select environment
        options:
          - stage
          - non_prod

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run Tests
        run: mvn clean install -Dkarate.env="${{ github.event.inputs.environment }}"

      - uses: actions/upload-artifact@v3
        with:
          name: regression_report
          path: ./target/karate-reports